name: Cloud Build & Release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Prevents Windows from canceling if Linux fails
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install System Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot dpkg

      - name: Install Node Dependencies
        run: npm install

      - name: Build and Publish Windows
        if: matrix.os == 'windows-latest'
        run: npm run build -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Linux
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux deb rpm AppImage --x64 --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}